spring:
  jpa:
    hibernate:

      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  datasource:
    # maria db
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3333/reservation_system
    username: root
    password: eodnxlavmf5wh!